/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// The console's words, in Chinese and English as the browser prefers (the
// sign-in pages choose the same way). `zh` is the shape's source: a key added
// to one and not the other fails the build.

import type { ConsoleErrorCode } from '../../src/admin-console/types.js';

export type ConsoleLocale = 'zh-CN' | 'en';

type Widen<T> = T extends string
  ? string
  : T extends (...args: infer Args) => string
    ? (...args: Args) => string
    : { [K in keyof T]: Widen<T[K]> };

const zh = {
  product: 'Maka 管理后台',
  notFound: {
    title: '找不到这个页面',
    body: '地址可能输错了，或者这个页面已经不在了。',
    home: '回到管理后台',
    back: '返回上一页',
    memberTitle: '找不到这个成员',
    memberBody: '链接可能不完整，或者这个地址指的不是一位成员。',
    providerTitle: '找不到这个模型提供商',
    providerBody: '它可能已经被删除了，或者链接不完整。',
    toMembers: '回到成员列表',
    toProviders: '回到模型提供商列表',
  },
  login: {
    title: '登录管理后台',
    continueWith: (provider: string) => `使用 ${provider} 登录`,
    or: '或',
    loading: '正在加载登录方式…',
    loadFailed: '暂时连不上服务器。',
    retry: '重试',
    foot: '只有组织管理员可以进入。',
    failures: {
      expired: '登录已过期，请重新登录。',
      cancelled: '登录没有完成，请重新登录。',
      not_admin: '这个账号不是组织管理员，不能进入管理后台。',
      email_not_verified: '这个账号的邮箱还没有验证。',
      domain_not_allowed: '这个邮箱的域名不能登录。',
      account_deactivated: '这个账号已被停用。',
      identity_conflict: '这个邮箱已经属于另一个账号，请联系管理员处理。',
      provider_error: '身份提供方没有完成登录，请稍后再试。',
    } as Record<string, string>,
  },
  nav: {
    label: '管理后台',
    groups: { organization: '组织', models: '模型', records: '记录' },
    members: '成员',
    quotas: '额度',
    'model-providers': '模型提供商',
    models: '已开放模型',
    usage: '用量',
    audit: '审计日志',
    signOut: '退出登录',
    signOutFailed: '退出登录失败',
    back: (label: string) => `返回${label}`,
  },
  common: {
    cancel: '取消',
    save: '保存',
    saving: '保存中…',
    delete: '删除',
    edit: '修改…',
    manageAria: (name: string) => `管理 ${name}`,
    moreActions: (name: string) => `${name} 的更多操作`,
    loading: '正在加载',
    loadFailed: '加载失败',
    retry: '重试',
    requestFailed: (status: number) => `服务器没有完成请求（${status}）`,
    unreachable: '连不上服务器，请检查网络后重试。',
    consoleUnavailable: '管理后台暂时打不开',
    unlimited: '不限制',
    never: '从未',
    units: (value: string) => `${value} 单位`,
    back: '上一步',
    failedBecause: (title: string, reason: string) => `${title}：${reason}`,
    withDetail: (message: string, detail: string) => `${message}（${detail}）`,
    changedElsewhere: '页面已更新',
    errors: {
      invalid_request: '请求的内容不正确',
      not_found: '它已经不在了，可能刚被别人删除。页面已更新。',
      revision_conflict: '刚才有人在别处改过它。页面已更新为最新内容，请再试一次。',
      catalog_expired: '模型列表已过期。请重新获取模型后再保存。',
      credentials_rejected: '提供商拒绝了这个密钥。请检查密钥是否正确、是否有访问权限。',
      provider_in_use: '这个提供商还有模型。先删除它的模型，再删除提供商。',
      name_taken: '这个名称已被另一个提供商使用，请换一个。',
      idempotency_conflict: '这次保存和上一次提交的内容不一致，请重新保存。',
    } satisfies Record<ConsoleErrorCode, string>,
  },
  members: {
    title: '成员',
    help: '用公司账号登录过 Maka 的人。新同事第一次登录时自动加入。',
    search: '搜索姓名或邮箱',
    columns: { person: '成员', role: '角色', lastLogin: '最近登录', devices: '设备' },
    admin: '管理员',
    member: '成员',
    deactivated: '已停用',
    devicesOnline: (count: number) => (count === 0 ? '无' : `${count} 台在线`),
    empty: '还没有人登录过',
    emptyHelp: '员工用公司账号登录 Maka 后会出现在这里。',
    noMatch: '没有匹配的成员',
    open: (name: string) => `打开 ${name}`,
  },
  member: {
    account: '账号',
    role: '角色',
    roleHelp: '管理员可以进入这个后台。',
    roleFailed: '修改角色失败',
    active: '启用中',
    activeHelp: '可以登录 Maka、使用公司的模型。',
    deactivatedHelp: '所有设备已退出登录，无法再登录。',
    deactivate: '停用…',
    activate: '重新启用',
    deactivateTitle: (name: string) => `停用 ${name}？`,
    deactivateBody: '他会立刻在所有设备上退出登录，也不能再登录，直到重新启用。',
    statusFailed: '修改状态失败',
    lastLogin: '最近登录',
    joined: '加入时间',
    identities: '登录方式',
    identitiesHelp: '这个人登录时使用的身份源账号。',
    noIdentities: '没有绑定的身份源',
    unlink: '解除绑定…',
    unlinkTitle: (provider: string) => `解除 ${provider} 绑定？`,
    unlinkBody:
      '通过这个身份源登录的设备会退出登录。之后他用这个身份源再次登录，会重新绑定到同一个邮箱。',
    unlinkFailed: '解除绑定失败',
    devices: '设备',
    devicesHelp: '登录过的 Maka 桌面端，最多显示最近 20 台。',
    noDevices: '还没有在任何设备上登录',
    unnamedDevice: '未命名设备',
    online: '在线',
    signedOut: '已退出',
    sessionExpired: '登录已过期',
    deviceDetail: (provider: string, lastUsed: string, since: string) =>
      `通过 ${provider} 登录 · 最近使用 ${lastUsed} · 登录于 ${since}`,
    revoke: '退出登录…',
    revokeTitle: (device: string) => `让 ${device} 退出登录？`,
    revokeBody: '这台设备会立刻退出登录，需要重新登录才能继续使用公司的模型。',
    revokeFailed: '让设备退出登录失败',
    revokeReasons: {
      account_deactivated: '账号停用',
      identity_unlinked: '解除绑定',
      admin_revoked: '管理员操作',
      signed_out: '自己退出',
      code_reuse: '安全原因',
      refresh_token_reuse: '安全原因',
    } as Record<string, string>,
    quotas: '额度',
    quotasHelp: '这个人每周期可用的加权用量。',
    week: '每周',
    month: '每月',
    quotaUsage: (used: string, limit: string, resets: string) =>
      `已用 ${used} / ${limit} · ${resets} 重置`,
    quotaUnlimited: (used: string) => `不限制 · 本期已用 ${used}`,
    quotaSource: { user: '单独设置', default: '组织默认', none: '' } as Record<string, string>,
    setQuota: '设置…',
  },
  providers: {
    title: '模型提供商',
    help: '组织在模型服务上的账号，例如 Anthropic、OpenAI 或 OpenRouter。先添加提供商，再从中选择开放给员工的模型。',
    add: '添加提供商',
    columns: { provider: '提供商', models: '模型', enabled: '启用' },
    summary: (count: number, enabled: boolean) =>
      `${count} 个模型 · ${enabled ? '已启用' : '已停用'}`,
    empty: '还没有模型提供商',
    emptyHelp:
      '模型提供商是组织在某个模型服务上的账号和密钥。添加一个，然后选择要开放给员工的模型。',
    open: (name: string) => `打开 ${name}`,
    enableAria: (name: string) => `启用 ${name}`,
    toggleFailed: '修改启用状态失败',
  },
  integrations: {
    groups: { official: '官方 API', aggregator: '聚合服务', cloud: '云平台', custom: '自定义服务' },
    custom: '兼容接口的服务',
    customLabel: (api: string) => `自定义服务 · ${api}`,
    descriptions: {
      anthropic: 'Claude 系列模型，用 API Key 接入',
      openai: 'GPT 系列模型，用 API Key 接入',
      gemini: 'Gemini 系列模型，用 API Key 接入',
      openrouter: '一个账号使用多家厂商的模型',
      vertex: '通过 Google Cloud 项目使用 Claude 和 Gemini 模型',
      custom: '兼容 Anthropic 或 OpenAI 接口的服务，例如公司自建的网关',
    },
    capabilities: {
      context: (size: string) => `${size} 上下文`,
      image: '图片',
      pdf: 'PDF',
      tools: '工具',
      thinking: '思考',
    },
  },
  addProvider: {
    chooseTitle: '添加模型提供商',
    chooseHelp: '选择要接入的服务。',
    detailsTitle: (label: string) => `添加 ${label}`,
    detailsHelp: '填写账号信息，然后获取这个账号可以使用的模型。',
    modelsTitle: '选择模型',
    modelsHelp: '勾选要开放给员工的模型。以后也可以在提供商页面继续添加。',
    name: '名称',
    nameHelp: '在后台区分不同账号用。留空则使用默认名称。',
    apiType: 'API 类型',
    apiTypeHelp: '这个服务兼容的接口。创建后不能修改。',
    baseUrl: 'API 地址',
    customBaseUrlHelp: '服务的 API 地址，例如 https://gateway.example.com/v1。',
    overrideBaseUrlHelp: '留空则使用官方地址。只有通过代理或私有网关访问时才需要填写。',
    advanced: '高级设置',
    apiKey: 'API Key',
    apiKeyHelp: '密钥加密保存在服务器上，员工的设备拿不到它。',
    serviceAccount: '服务账号 JSON',
    serviceAccountHelp: '粘贴 Google Cloud 服务账号密钥文件的全部内容。它加密保存在服务器上。',
    projectId: '项目 ID',
    region: '区域',
    regionHelp: '例如 global 或 us-east5。',
    required: '请填写这一项',
    nameTooLong: (max: string) => `名称不能超过 ${max} 个字符`,
    keyTooLong: (max: string) => `密钥不能超过 ${max} 个字符`,
    invalidUrl:
      '请填写以 https:// 或 http:// 开头的地址，不能带用户名、密码、查询参数（?）或 # 片段',
    invalidProjectId:
      '项目 ID 格式不对：6 到 30 个字符，以小写字母开头，只含小写字母、数字和连字符',
    invalidRegion: '区域格式不对：2 到 40 个小写字母、数字或连字符',
    invalidServiceAccount:
      '这不是有效的服务账号密钥：需要是 JSON，并包含 "type": "service_account"、client_email 和 private_key',
    discover: '获取模型',
    discovering: '正在获取模型…',
    catalogCredentials: '提供商拒绝了这个密钥。请检查密钥是否正确、是否有读取模型列表的权限。',
    catalogUnavailable: '暂时连不上提供商。请检查 API 地址和服务器的网络，然后重试。',
    catalogInvalid: '提供商返回的模型列表无法识别。请确认 API 地址和 API 类型，或稍后重试。',
    discoverFailed: '获取模型失败',
    saveProviderOnly: '只保存提供商',
    saveAndPublish: (count: number) =>
      count === 0 ? '保存并开放模型' : `保存并开放 ${count} 个模型`,
    saving: '正在保存…',
    saveFailed: '保存提供商失败',
    renamed: (name: string) => `名称已被使用，已保存为「${name}」`,
    catalogRefreshed: '模型列表已过期，已重新获取。请确认选择后再保存。',
    alreadySaved: '上一次保存其实已经完成，提供商已添加。',
  },
  addModels: {
    title: (name: string) => `从 ${name} 添加模型`,
    help: '勾选要开放给员工的模型。已添加的模型不会重复添加。',
    publish: (count: number) => (count === 0 ? '开放模型' : `开放 ${count} 个模型`),
    publishing: '正在开放…',
    publishFailed: '开放模型失败',
    refreshed: '这个提供商刚刚有变化，已重新获取模型列表。请确认选择后再保存。',
    credentials: '提供商拒绝了保存的密钥。请在「设置」里更换密钥后重试。',
    alreadyPublished: '上一次开放其实已经完成。',
  },
  picker: {
    search: '搜索模型名称或 ID',
    count: (selected: number, total: number) => `已选 ${selected} 个 · 共 ${total} 个`,
    selectAll: '全选',
    selectResults: '全选搜索结果',
    clear: '清空',
    added: '已添加',
    noMatch: '没有匹配的模型',
    empty: '这个账号没有可以开放的模型',
    skipped: (count: number) => `另有 ${count} 个模型无法识别，没有列出。`,
    listLabel: '可开放的模型',
  },
  provider: {
    enabled: '已启用',
    disabled: '已停用',
    disabledNotice: '这个提供商已停用，它的模型暂时不能使用。重新启用后恢复。',
    models: '模型',
    modelsHelp: '从这个提供商开放给员工的模型。',
    addModels: '添加模型',
    noModels: '还没有从这个提供商开放模型',
    noModelsHelp: '添加模型后，员工就能在 Maka 里选择它们。',
    columns: { model: '模型', enabled: '启用' },
    settings: '设置',
    name: '名称',
    renameTitle: '修改名称',
    renameFailed: '修改名称失败',
    integration: '接入方式',
    fixedHelp: '接入方式和地址创建后不能修改。要换成别的账号或地址，请添加一个新的提供商。',
    baseUrl: 'API 地址',
    defaultBaseUrl: '官方地址',
    projectId: '项目 ID',
    region: '区域',
    apiKey: 'API Key',
    serviceAccount: '服务账号',
    credentialHelp: '加密保存在服务器上，不会显示出来。',
    replaceKey: '更换密钥…',
    replaceServiceAccount: '更换服务账号…',
    replaceKeyTitle: '更换 API Key',
    replaceServiceAccountTitle: '更换服务账号',
    replaceHelp: '新的密钥会先经过提供商验证，通过后才替换现有的。',
    newApiKey: '新的 API Key',
    newServiceAccount: '新的服务账号 JSON',
    verifying: '正在验证…',
    replace: '更换',
    replaced: '密钥已更换',
    replaceFailed: '更换密钥失败',
    delete: '删除提供商',
    deleteHelp: '删除这个提供商和它保存的密钥。',
    deleteBlocked: (count: number) =>
      `还有 ${count} 个模型来自这个提供商，先在上面的模型列表里删除它们。`,
    deleteAction: '删除…',
    deleteTitle: (name: string) => `删除 ${name}？`,
    deleteBody: '提供商和它保存的密钥会被删除，不能恢复。',
    deleteFailed: '删除提供商失败',
  },
  models: {
    title: '已开放模型',
    help: '员工可以在 Maka 里选择的模型。每个模型来自一个模型提供商。',
    search: '搜索模型',
    filterProvider: '按提供商筛选',
    allProviders: '全部提供商',
    columns: { model: '模型', provider: '提供商', quota: '额度倍率', enabled: '启用' },
    providerDisabled: '提供商已停用',
    unmetered: '不计额度',
    weight: (value: string) => `${value}×`,
    empty: '还没有模型',
    emptyHelp: '先添加模型提供商，再选择要开放给员工的模型。',
    toProviders: '前往模型提供商',
    noMatch: '没有匹配的模型',
    enableAria: (name: string) => `启用 ${name}`,
    openProvider: (name: string) => `打开提供商 ${name}`,
    toggleFailed: '修改启用状态失败',
  },
  model: {
    settings: '设置',
    settingsTitle: '模型设置',
    displayName: '显示名称',
    displayNameHelp: '员工在模型列表里看到的名称。',
    costWeight: '额度倍率',
    costWeightHelp: '用量乘以这个倍率计入额度。1 为标准，0 为不计额度，最大 10000。',
    sortOrder: '显示顺序',
    sortOrderHelp: '数字越小越靠前。',
    invalidName: '请填写名称',
    nameTooLong: (max: string) => `名称不能超过 ${max} 个字符`,
    invalidWeight: (max: string) => `请填写 0 到 ${max} 之间的数字`,
    invalidOrder: (max: string) => `请填写 0 到 ${max} 之间的整数`,
    saveFailed: '保存模型设置失败',
    source: (provider: string, model: string) => `来自 ${provider} · ${model}`,
    delete: '删除',
    deleteTitle: (name: string) => `删除 ${name}？`,
    deleteBody: '员工将不能再选择这个模型。正在用它的对话需要换一个模型才能继续。',
    deleteFailed: '删除模型失败',
    actions: '操作',
  },
  quotas: {
    defaults: '组织默认额度',
    defaultsHelp: '每人每个周期可用的加权用量。不设置就不限制。',
    week: '每周',
    weekHelp: '每周一 00:00（UTC）重置。',
    month: '每月',
    monthHelp: '每月 1 日 00:00（UTC）重置。',
    people: '个人额度',
    peopleHelp: '为个别成员单独设置，覆盖组织默认。',
    addPerson: '添加',
    columns: { person: '成员', week: '每周', month: '每月' },
    noPeople: '没有单独设置的成员',
    inherit: '跟随默认',
    units:
      '单位是加权 token：输入 ×1、输出 ×5、缓存写入 ×1.25、缓存读取 ×0.1，再乘模型的成本权重。',
    dialogTitle: (what: string) => `设置${what}额度`,
    limit: '额度（单位）',
    limitPlaceholder: '例如 5000000',
    unlimitedChoice: '不限制',
    inheritChoice: '跟随组织默认',
    personField: '成员',
    personPlaceholder: '选择成员',
    periodField: '周期',
    invalidLimit: '请填写 0 或更大的数字',
    failed: '保存额度失败',
  },
  usage: {
    range: (days: number) => `${days} 天`,
    rangeLabel: '时间范围',
    overview: '概览',
    requests: '请求',
    errors: '失败',
    inputTokens: '输入 token',
    outputTokens: '输出 token',
    units: '加权用量',
    byPerson: '按成员',
    byModel: '按模型',
    columns: {
      person: '成员',
      model: '模型',
      requests: '请求',
      input: '输入',
      output: '输出',
      units: '用量',
    },
    empty: '这段时间没有用量',
    since: (date: string) => `自 ${date} 起`,
    cacheTokens: '缓存 token',
    cacheDetail: (read: string, write: string) => `读取 ${read} · 写入 ${write}`,
    estimated: (count: string) =>
      `其中 ${count} 次请求的 token 数由服务器估算：提供商没有返回用量。`,
  },
  audit: {
    title: '审计日志',
    help: '谁在什么时候做了什么。管理后台和命令行的每次改动都会记在这里。',
    filter: '类型',
    filters: {
      all: '全部',
      'admin.': '管理后台登录',
      'signin.': '登录被拒',
      'session.': '设备会话',
      'user.': '成员',
      'identity.': '登录方式',
      'model_provider.': '模型提供商',
      'model.': '模型',
      'quota.': '额度',
    } as Record<string, string>,
    columns: { time: '时间', actor: '操作者', action: '操作', target: '对象' },
    system: '系统',
    organizationDefault: '组织默认',
    cli: '命令行',
    loadMore: '加载更多',
    empty: '没有记录',
    actions: {
      'admin.signed_in': '登录管理后台',
      'admin.signed_out': '退出管理后台',
      'admin.signin_refused': '被拒绝进入管理后台',
      'signin.refused': '登录被拒',
      'session.created': '设备登录',
      'session.revoked': '设备退出登录',
      'user.role_changed': '修改角色',
      'user.deactivated': '停用成员',
      'user.activated': '重新启用成员',
      'identity.unlinked': '解除登录方式绑定',
      'identity.linked': '绑定登录方式',
      'identity.conflict': '登录方式冲突',
      'user.created': '新成员加入',
      'model_provider.created': '添加模型提供商',
      'model_provider.updated': '修改模型提供商',
      'model_provider.deleted': '删除模型提供商',
      'model.published': '开放模型',
      'model.updated': '修改模型',
      'model.deleted': '删除模型',
      'quota.set': '设置额度',
      'quota.removed': '移除额度',
    } as Record<string, string>,
  },
};

export type ConsoleCopy = Widen<typeof zh>;

const en: ConsoleCopy = {
  product: 'Maka Admin',
  notFound: {
    title: "We couldn't find that page",
    body: 'The address may be mistyped, or the page is no longer here.',
    home: 'Go to the console',
    back: 'Go back',
    memberTitle: "We couldn't find that member",
    memberBody: 'The link may be incomplete, or it does not point to a member.',
    providerTitle: "We couldn't find that LLM provider",
    providerBody: 'It may have been deleted, or the link is incomplete.',
    toMembers: 'Back to members',
    toProviders: 'Back to LLM Provider',
  },
  login: {
    title: 'Sign in to Maka Admin',
    continueWith: (provider) => `Continue with ${provider}`,
    or: 'OR',
    loading: 'Loading sign-in options…',
    loadFailed: 'The server cannot be reached right now.',
    retry: 'Try again',
    foot: 'Only organization administrators can sign in.',
    failures: {
      expired: 'That sign-in expired. Sign in again.',
      cancelled: 'Signing in did not finish. Sign in again.',
      not_admin: 'This account is not an organization administrator.',
      email_not_verified: "This account's email address is not verified.",
      domain_not_allowed: 'This email domain cannot sign in.',
      account_deactivated: 'This account has been deactivated.',
      identity_conflict: 'This email belongs to another account. Ask an administrator.',
      provider_error: 'The identity provider could not sign you in. Try again later.',
    },
  },
  nav: {
    label: 'Admin console',
    groups: { organization: 'Organization', models: 'Models', records: 'Records' },
    members: 'Members',
    quotas: 'Allowances',
    'model-providers': 'LLM Provider',
    models: 'Published models',
    usage: 'Usage',
    audit: 'Audit log',
    signOut: 'Sign out',
    signOutFailed: 'Could not sign out',
    back: (label) => `Back to ${label}`,
  },
  common: {
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    edit: 'Edit…',
    manageAria: (name) => `Manage ${name}`,
    moreActions: (name) => `More actions for ${name}`,
    loading: 'Loading',
    loadFailed: 'Could not load',
    retry: 'Retry',
    requestFailed: (status) => `The server did not complete the request (${status})`,
    unreachable: 'The server cannot be reached. Check the network and try again.',
    consoleUnavailable: 'The console cannot be opened right now',
    unlimited: 'Unlimited',
    never: 'Never',
    units: (value) => `${value} units`,
    back: 'Back',
    failedBecause: (title, reason) => `${title}: ${reason}`,
    withDetail: (message, detail) => `${message} (${detail})`,
    changedElsewhere: 'Page updated',
    errors: {
      invalid_request: 'The request was not valid',
      not_found: 'It is gone; someone may have just deleted it. The page has been updated.',
      revision_conflict:
        'Someone changed it elsewhere a moment ago. The page now shows the latest; try again.',
      catalog_expired: 'The model list has expired. Fetch the models again, then save.',
      credentials_rejected:
        'The provider refused this key. Check that it is correct and has access.',
      provider_in_use:
        'This provider still has models. Delete its models before deleting the provider.',
      name_taken: 'Another provider already has this name. Choose another.',
      idempotency_conflict: 'This save differs from the one sent before. Save again.',
    },
  },
  members: {
    title: 'Members',
    help: 'People who have signed in to Maka with their company account. Someone new joins the first time they sign in.',
    search: 'Search by name or email',
    columns: { person: 'Member', role: 'Role', lastLogin: 'Last sign-in', devices: 'Devices' },
    admin: 'Admin',
    member: 'Member',
    deactivated: 'Deactivated',
    devicesOnline: (count) =>
      count === 0 ? 'None' : count === 1 ? '1 signed in' : `${count} signed in`,
    empty: 'Nobody has signed in yet',
    emptyHelp: 'People appear here after they sign in to Maka with their company account.',
    noMatch: 'No matching members',
    open: (name) => `Open ${name}`,
  },
  member: {
    account: 'Account',
    role: 'Role',
    roleHelp: 'Admins can open this console.',
    roleFailed: 'Could not change the role',
    active: 'Active',
    activeHelp: "Can sign in to Maka and use the company's models.",
    deactivatedHelp: 'Signed out on every device and cannot sign in.',
    deactivate: 'Deactivate…',
    activate: 'Reactivate',
    deactivateTitle: (name) => `Deactivate ${name}?`,
    deactivateBody:
      'They are signed out on every device at once and cannot sign in again until reactivated.',
    statusFailed: 'Could not change the status',
    lastLogin: 'Last sign-in',
    joined: 'Joined',
    identities: 'Sign-in methods',
    identitiesHelp: 'The identity provider accounts this person signs in with.',
    noIdentities: 'No linked identity provider',
    unlink: 'Unlink…',
    unlinkTitle: (provider) => `Unlink ${provider}?`,
    unlinkBody:
      'Devices signed in through it are signed out. Signing in through it again links it back to the same email.',
    unlinkFailed: 'Could not unlink',
    devices: 'Devices',
    devicesHelp: 'Maka desktops they have signed in on, the 20 most recent.',
    noDevices: 'Not signed in on any device yet',
    unnamedDevice: 'Unnamed device',
    online: 'Signed in',
    signedOut: 'Signed out',
    sessionExpired: 'Sign-in expired',
    deviceDetail: (provider, lastUsed, since) =>
      `Through ${provider} · last used ${lastUsed} · signed in ${since}`,
    revoke: 'Sign out…',
    revokeTitle: (device) => `Sign ${device} out?`,
    revokeBody:
      "The device is signed out at once and must sign in again to use the company's models.",
    revokeFailed: 'Could not sign the device out',
    revokeReasons: {
      account_deactivated: 'account deactivated',
      identity_unlinked: 'sign-in unlinked',
      admin_revoked: 'by an admin',
      signed_out: 'signed out',
      code_reuse: 'security',
      refresh_token_reuse: 'security',
    },
    quotas: 'Allowances',
    quotasHelp: 'How much weighted usage this person may use each period.',
    week: 'Weekly',
    month: 'Monthly',
    quotaUsage: (used, limit, resets) => `${used} of ${limit} used · resets ${resets}`,
    quotaUnlimited: (used) => `Unlimited · ${used} used this period`,
    quotaSource: { user: 'their own', default: 'organization default', none: '' },
    setQuota: 'Set…',
  },
  providers: {
    title: 'LLM Provider',
    help: "Your organization's accounts with model services, such as Anthropic, OpenAI or OpenRouter. Add a provider, then choose the models employees can use.",
    add: 'Add provider',
    columns: { provider: 'Provider', models: 'Models', enabled: 'Enabled' },
    summary: (count, enabled) =>
      `${count === 1 ? '1 model' : `${count} models`} · ${enabled ? 'Enabled' : 'Disabled'}`,
    empty: 'No LLM providers yet',
    emptyHelp:
      "A provider is your organization's account and key with a model service. Add one, then choose the models employees can use.",
    open: (name) => `Open ${name}`,
    enableAria: (name) => `Enable ${name}`,
    toggleFailed: 'Could not enable or disable the provider',
  },
  integrations: {
    groups: {
      official: 'Official APIs',
      aggregator: 'Aggregators',
      cloud: 'Cloud platforms',
      custom: 'Custom services',
    },
    custom: 'Compatible API service',
    customLabel: (api) => `Custom service · ${api}`,
    descriptions: {
      anthropic: 'Claude models, with an API key',
      openai: 'GPT models, with an API key',
      gemini: 'Gemini models, with an API key',
      openrouter: 'Models from many vendors with one account',
      vertex: 'Claude and Gemini models through a Google Cloud project',
      custom: 'A service that speaks the Anthropic or OpenAI API, such as your own gateway',
    },
    capabilities: {
      context: (size) => `${size} context`,
      image: 'Images',
      pdf: 'PDF',
      tools: 'Tools',
      thinking: 'Thinking',
    },
  },
  addProvider: {
    chooseTitle: 'Add an LLM provider',
    chooseHelp: 'Choose the service to add.',
    detailsTitle: (label) => `Add ${label}`,
    detailsHelp: 'Enter the account details, then fetch the models this account can use.',
    modelsTitle: 'Choose models',
    modelsHelp:
      "Check the models employees can use. You can add more later from the provider's page.",
    name: 'Name',
    nameHelp: 'Tells accounts apart in this console. Leave it empty for the default name.',
    apiType: 'API type',
    apiTypeHelp: 'The API this service is compatible with. It cannot be changed later.',
    baseUrl: 'API address',
    customBaseUrlHelp: "The service's API address, for example https://gateway.example.com/v1.",
    overrideBaseUrlHelp:
      'Leave empty for the official address. Only needed through a proxy or a private gateway.',
    advanced: 'Advanced settings',
    apiKey: 'API key',
    apiKeyHelp: "The key is kept encrypted on the server; employees' devices never get it.",
    serviceAccount: 'Service account JSON',
    serviceAccountHelp:
      'Paste the whole Google Cloud service account key file. It is kept encrypted on the server.',
    projectId: 'Project ID',
    region: 'Region',
    regionHelp: 'For example global or us-east5.',
    required: 'Fill this in',
    nameTooLong: (max) => `Use at most ${max} characters`,
    keyTooLong: (max) => `Use at most ${max} characters`,
    invalidUrl:
      'Enter an address starting with https:// or http://, with no user name, password, query (?) or # fragment',
    invalidProjectId:
      'Not a valid project ID: 6 to 30 characters, starting with a lowercase letter, using only lowercase letters, digits and hyphens',
    invalidRegion: 'Not a valid region: 2 to 40 lowercase letters, digits or hyphens',
    invalidServiceAccount:
      'This is not a valid service account key: it must be JSON with "type": "service_account", client_email and private_key',
    discover: 'Fetch models',
    discovering: 'Fetching models…',
    catalogCredentials:
      'The provider refused this key. Check that it is correct and allowed to list models.',
    catalogUnavailable:
      "The provider cannot be reached right now. Check the API address and the server's network, then try again.",
    catalogInvalid:
      "The provider's model list could not be read. Check the API address and type, or try again later.",
    discoverFailed: 'Could not fetch models',
    saveProviderOnly: 'Save provider only',
    saveAndPublish: (count) =>
      count === 0
        ? 'Save and publish models'
        : `Save and publish ${count === 1 ? '1 model' : `${count} models`}`,
    saving: 'Saving…',
    saveFailed: 'Could not save the provider',
    renamed: (name) => `That name was taken; saved as “${name}”`,
    catalogRefreshed:
      'The model list had expired and was fetched again. Check your choice and save.',
    alreadySaved: 'The earlier save went through; the provider has been added.',
  },
  addModels: {
    title: (name) => `Add models from ${name}`,
    help: 'Check the models employees can use. Models already added are not added twice.',
    publish: (count) =>
      count === 0 ? 'Publish models' : `Publish ${count === 1 ? '1 model' : `${count} models`}`,
    publishing: 'Publishing…',
    publishFailed: 'Could not publish the models',
    refreshed:
      'This provider changed a moment ago, so its model list was fetched again. Check your choice and save.',
    credentials: 'The provider refused the saved key. Replace it under Settings and try again.',
    alreadyPublished: 'The earlier publish went through.',
  },
  picker: {
    search: 'Search model name or ID',
    count: (selected, total) => `${selected} of ${total} selected`,
    selectAll: 'Select all',
    selectResults: 'Select all results',
    clear: 'Clear',
    added: 'Added',
    noMatch: 'No matching models',
    empty: 'This account has no models that can be published',
    skipped: (count) =>
      `${count === 1 ? '1 more model' : `${count} more models`} could not be read and are not listed.`,
    listLabel: 'Models to publish',
  },
  provider: {
    enabled: 'Enabled',
    disabled: 'Disabled',
    disabledNotice:
      'This provider is disabled, so its models cannot be used for now. Enable it again to bring them back.',
    models: 'Models',
    modelsHelp: 'The models from this provider that employees can use.',
    addModels: 'Add models',
    noModels: 'No models published from this provider yet',
    noModelsHelp: 'Once you add models, employees can choose them in Maka.',
    columns: { model: 'Model', enabled: 'Enabled' },
    settings: 'Settings',
    name: 'Name',
    renameTitle: 'Rename',
    renameFailed: 'Could not rename',
    integration: 'Service',
    fixedHelp:
      'The service and address are fixed once created. For another account or address, add a new provider.',
    baseUrl: 'API address',
    defaultBaseUrl: 'official address',
    projectId: 'Project ID',
    region: 'Region',
    apiKey: 'API key',
    serviceAccount: 'Service account',
    credentialHelp: 'Kept encrypted on the server and never shown.',
    replaceKey: 'Replace key…',
    replaceServiceAccount: 'Replace service account…',
    replaceKeyTitle: 'Replace the API key',
    replaceServiceAccountTitle: 'Replace the service account',
    replaceHelp:
      'The provider checks the new key first; it replaces the current one only if accepted.',
    newApiKey: 'New API key',
    newServiceAccount: 'New service account JSON',
    verifying: 'Checking…',
    replace: 'Replace',
    replaced: 'Key replaced',
    replaceFailed: 'Could not replace the key',
    delete: 'Delete provider',
    deleteHelp: 'Delete this provider and its saved key.',
    deleteBlocked: (count) =>
      `${count === 1 ? '1 model still comes' : `${count} models still come`} from this provider. Delete them in the model list above first.`,
    deleteAction: 'Delete…',
    deleteTitle: (name) => `Delete ${name}?`,
    deleteBody: 'The provider and its saved key are deleted. This cannot be undone.',
    deleteFailed: 'Could not delete the provider',
  },
  models: {
    title: 'Published models',
    help: 'The models employees can choose in Maka. Each comes from one LLM provider.',
    search: 'Search models',
    filterProvider: 'Filter by provider',
    allProviders: 'All providers',
    columns: {
      model: 'Model',
      provider: 'Provider',
      quota: 'Allowance rate',
      enabled: 'Enabled',
    },
    providerDisabled: 'Provider disabled',
    unmetered: 'Not counted',
    weight: (value) => `${value}×`,
    empty: 'No models yet',
    emptyHelp: 'Add an LLM provider first, then choose the models employees can use.',
    toProviders: 'Go to LLM Provider',
    noMatch: 'No matching models',
    enableAria: (name) => `Enable ${name}`,
    openProvider: (name) => `Open the provider ${name}`,
    toggleFailed: 'Could not enable or disable the model',
  },
  model: {
    settings: 'Settings',
    settingsTitle: 'Model settings',
    displayName: 'Display name',
    displayNameHelp: 'The name employees see in their model list.',
    costWeight: 'Allowance rate',
    costWeightHelp:
      'Usage counts toward allowances times this rate. 1 is standard, 0 is not counted, at most 10000.',
    sortOrder: 'Display order',
    sortOrderHelp: 'Lower numbers come first.',
    invalidName: 'Enter a name',
    nameTooLong: (max) => `Use at most ${max} characters`,
    invalidWeight: (max) => `Enter a number from 0 to ${max}`,
    invalidOrder: (max) => `Enter a whole number from 0 to ${max}`,
    saveFailed: 'Could not save the model settings',
    source: (provider, model) => `From ${provider} · ${model}`,
    delete: 'Delete',
    deleteTitle: (name) => `Delete ${name}?`,
    deleteBody:
      'Employees can no longer choose this model. Conversations using it need another model to go on.',
    deleteFailed: 'Could not delete the model',
    actions: 'Actions',
  },
  quotas: {
    defaults: 'Organization defaults',
    defaultsHelp: 'How much weighted usage each person may use per period. Unset means unlimited.',
    week: 'Weekly',
    weekHelp: 'Resets every Monday at 00:00 UTC.',
    month: 'Monthly',
    monthHelp: 'Resets on the 1st at 00:00 UTC.',
    people: 'Individual allowances',
    peopleHelp: 'Set for particular members, in place of the defaults.',
    addPerson: 'Add',
    columns: { person: 'Member', week: 'Weekly', month: 'Monthly' },
    noPeople: 'Nobody has an allowance of their own',
    inherit: 'Default',
    units:
      "Units are weighted tokens: input ×1, output ×5, cache writes ×1.25, cache reads ×0.1, times the model's cost weight.",
    dialogTitle: (what) => `Set the ${what.toLowerCase()} allowance`,
    limit: 'Allowance (units)',
    limitPlaceholder: 'For example 5000000',
    unlimitedChoice: 'Unlimited',
    inheritChoice: 'Use the organization default',
    personField: 'Member',
    personPlaceholder: 'Choose a member',
    periodField: 'Period',
    invalidLimit: 'Enter a number, 0 or more',
    failed: 'Could not save the allowance',
  },
  usage: {
    range: (days) => `${days} days`,
    rangeLabel: 'Period',
    overview: 'Overview',
    requests: 'Requests',
    errors: 'Failed',
    inputTokens: 'Input tokens',
    outputTokens: 'Output tokens',
    units: 'Weighted usage',
    byPerson: 'By member',
    byModel: 'By model',
    columns: {
      person: 'Member',
      model: 'Model',
      requests: 'Requests',
      input: 'Input',
      output: 'Output',
      units: 'Usage',
    },
    empty: 'No usage in this period',
    since: (date) => `Since ${date}`,
    cacheTokens: 'Cache tokens',
    cacheDetail: (read, write) => `${read} read · ${write} written`,
    estimated: (count) =>
      `Tokens for ${count} of these requests were estimated by the server: the provider did not report usage.`,
  },
  audit: {
    title: 'Audit log',
    help: 'Who did what, and when. Every change made here or on the command line is recorded.',
    filter: 'Kind',
    filters: {
      all: 'All',
      'admin.': 'Console sign-ins',
      'signin.': 'Refused sign-ins',
      'session.': 'Device sessions',
      'user.': 'Members',
      'identity.': 'Sign-in methods',
      'model_provider.': 'LLM providers',
      'model.': 'Models',
      'quota.': 'Allowances',
    },
    columns: { time: 'Time', actor: 'By', action: 'Action', target: 'Target' },
    system: 'System',
    organizationDefault: 'Organization default',
    cli: 'Command line',
    loadMore: 'Load more',
    empty: 'Nothing recorded',
    actions: {
      'admin.signed_in': 'Signed in to the console',
      'admin.signed_out': 'Signed out of the console',
      'admin.signin_refused': 'Refused entry to the console',
      'signin.refused': 'Sign-in refused',
      'session.created': 'Device signed in',
      'session.revoked': 'Device signed out',
      'user.role_changed': 'Role changed',
      'user.deactivated': 'Member deactivated',
      'user.activated': 'Member reactivated',
      'identity.unlinked': 'Sign-in method unlinked',
      'identity.linked': 'Sign-in method linked',
      'identity.conflict': 'Sign-in method conflict',
      'user.created': 'Member joined',
      'model_provider.created': 'LLM provider added',
      'model_provider.updated': 'LLM provider changed',
      'model_provider.deleted': 'LLM provider deleted',
      'model.published': 'Model published',
      'model.updated': 'Model changed',
      'model.deleted': 'Model deleted',
      'quota.set': 'Allowance set',
      'quota.removed': 'Allowance removed',
    },
  },
};

export function consoleLocale(): ConsoleLocale {
  return navigator.language?.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en';
}

export function getCopy(locale: ConsoleLocale): ConsoleCopy {
  return locale === 'zh-CN' ? zh : en;
}
