/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// The console's words, in Chinese and English as the browser prefers (the
// sign-in pages choose the same way). `zh` is the shape's source: a key added
// to one and not the other fails the build.

export type ConsoleLocale = 'zh-CN' | 'en';

type Widen<T> = T extends string
  ? string
  : T extends (...args: infer Args) => string
    ? (...args: Args) => string
    : { [K in keyof T]: Widen<T[K]> };

const zh = {
  product: 'Maka 管理后台',
  notFound: {
    title: '找不到这个页面',
    body: '地址可能输错了，或者这个页面已经不在了。',
    home: '回到管理后台',
    back: '返回上一页',
    memberTitle: '找不到这个成员',
    memberBody: '链接可能不完整，或者这个地址指的不是一位成员。',
    modelTitle: '找不到这个模型',
    modelBody: '它可能已经被删除了，或者链接不完整。',
    toMembers: '回到成员列表',
    toModels: '回到模型列表',
  },
  login: {
    title: '登录管理后台',
    continueWith: (provider: string) => `使用 ${provider} 登录`,
    or: '或',
    loading: '正在加载登录方式…',
    loadFailed: '暂时连不上服务器。',
    retry: '重试',
    foot: '只有组织管理员可以进入。',
    failures: {
      expired: '登录已过期，请重新登录。',
      cancelled: '登录没有完成，请重新登录。',
      not_admin: '这个账号不是组织管理员，不能进入管理后台。',
      email_not_verified: '这个账号的邮箱还没有验证。',
      domain_not_allowed: '这个邮箱的域名不能登录。',
      account_deactivated: '这个账号已被停用。',
      identity_conflict: '这个邮箱已经属于另一个账号，请联系管理员处理。',
      provider_error: '身份提供方没有完成登录，请稍后再试。',
    } as Record<string, string>,
  },
  nav: {
    label: '管理后台',
    groups: { organization: '组织', models: '模型', records: '记录' },
    members: '成员',
    quotas: '额度',
    models: '模型',
    upstreams: '模型提供商',
    usage: '用量',
    audit: '审计日志',
    signOut: '退出登录',
    signOutFailed: '退出登录失败',
    back: (label: string) => `返回${label}`,
  },
  common: {
    cancel: '取消',
    save: '保存',
    saving: '保存中…',
    add: '添加',
    remove: '移除',
    delete: '删除',
    edit: '修改…',
    manage: '管理',
    manageAria: (name: string) => `管理 ${name}`,
    moreActions: (name: string) => `${name} 的更多操作`,
    loading: '正在加载',
    loadFailed: '加载失败',
    retry: '重试',
    saveFailed: '保存失败',
    requestFailed: (status: number) => `服务器没有完成请求（${status}）`,
    unreachable: '连不上服务器，请检查网络后重试。',
    consoleUnavailable: '管理后台暂时打不开',
    disabled: '已停用',
    unlimited: '不限制',
    never: '从未',
    units: (value: string) => `${value} 单位`,
  },
  members: {
    title: '成员',
    help: '用公司账号登录过 Maka 的人。新同事第一次登录时自动加入。',
    search: '搜索姓名或邮箱',
    columns: { person: '成员', role: '角色', lastLogin: '最近登录', devices: '设备' },
    admin: '管理员',
    member: '成员',
    deactivated: '已停用',
    devicesOnline: (count: number) => (count === 0 ? '无' : `${count} 台在线`),
    empty: '还没有人登录过',
    emptyHelp: '员工用公司账号登录 Maka 后会出现在这里。',
    noMatch: '没有匹配的成员',
    open: (name: string) => `打开 ${name}`,
  },
  member: {
    account: '账号',
    role: '角色',
    roleHelp: '管理员可以进入这个后台。',
    roleFailed: '修改角色失败',
    active: '启用中',
    activeHelp: '可以登录 Maka、使用公司的模型。',
    deactivatedHelp: '所有设备已退出登录，无法再登录。',
    deactivate: '停用…',
    activate: '重新启用',
    deactivateTitle: (name: string) => `停用 ${name}？`,
    deactivateBody: '他会立刻在所有设备上退出登录，也不能再登录，直到重新启用。',
    statusFailed: '修改状态失败',
    lastLogin: '最近登录',
    joined: '加入时间',
    identities: '登录方式',
    identitiesHelp: '这个人登录时使用的身份源账号。',
    noIdentities: '没有绑定的身份源',
    unlink: '解除绑定…',
    unlinkTitle: (provider: string) => `解除 ${provider} 绑定？`,
    unlinkBody:
      '通过这个身份源登录的设备会退出登录。之后他用这个身份源再次登录，会重新绑定到同一个邮箱。',
    unlinkFailed: '解除绑定失败',
    devices: '设备',
    devicesHelp: '登录过的 Maka 桌面端，最多显示最近 20 台。',
    noDevices: '还没有在任何设备上登录',
    unnamedDevice: '未命名设备',
    online: '在线',
    signedOut: '已退出',
    sessionExpired: '登录已过期',
    deviceDetail: (provider: string, lastUsed: string, since: string) =>
      `通过 ${provider} 登录 · 最近使用 ${lastUsed} · 登录于 ${since}`,
    revoke: '退出登录…',
    revokeTitle: (device: string) => `让 ${device} 退出登录？`,
    revokeBody: '这台设备会立刻退出登录，需要重新登录才能继续使用公司的模型。',
    revokeFailed: '让设备退出登录失败',
    revokeReasons: {
      account_deactivated: '账号停用',
      identity_unlinked: '解除绑定',
      admin_revoked: '管理员操作',
      signed_out: '自己退出',
      code_reuse: '安全原因',
      refresh_token_reuse: '安全原因',
    } as Record<string, string>,
    quotas: '额度',
    quotasHelp: '这个人每周期可用的加权用量。',
    week: '每周',
    month: '每月',
    quotaUsage: (used: string, limit: string, resets: string) =>
      `已用 ${used} / ${limit} · ${resets} 重置`,
    quotaUnlimited: (used: string) => `不限制 · 本期已用 ${used}`,
    quotaSource: { user: '单独设置', default: '组织默认', none: '' } as Record<string, string>,
    setQuota: '设置…',
  },
  quotas: {
    defaults: '组织默认额度',
    defaultsHelp: '每人每个周期可用的加权用量。不设置就不限制。',
    week: '每周',
    weekHelp: '每周一 00:00（UTC）重置。',
    month: '每月',
    monthHelp: '每月 1 日 00:00（UTC）重置。',
    people: '个人额度',
    peopleHelp: '为个别成员单独设置，覆盖组织默认。',
    addPerson: '添加',
    columns: { person: '成员', week: '每周', month: '每月' },
    noPeople: '没有单独设置的成员',
    inherit: '跟随默认',
    units:
      '单位是加权 token：输入 ×1、输出 ×5、缓存写入 ×1.25、缓存读取 ×0.1，再乘模型的成本权重。',
    dialogTitle: (what: string) => `设置${what}额度`,
    limit: '额度（单位）',
    limitPlaceholder: '例如 5000000',
    unlimitedChoice: '不限制',
    inheritChoice: '跟随组织默认',
    personField: '成员',
    personPlaceholder: '选择成员',
    periodField: '周期',
    invalidLimit: '请填写 0 或更大的数字',
    failed: '保存额度失败',
  },
  models: {
    title: '模型',
    help: '员工在 Maka 里能选到的模型。启用后所有人可用。',
    add: '添加模型',
    empty: '还没有模型',
    emptyHelp: '先添加模型提供商，再添加模型并指定它走哪个提供商。',
    noRoute: '没有路由',
    via: (names: string) => `经 ${names}`,
    enableAria: (name: string) => `启用 ${name}`,
    toggleFailed: '修改模型失败',
    addTitle: '添加模型',
    id: '模型 ID',
    idHelp: 'Maka 请求时使用的名字。优先用官方 ID，例如 claude-sonnet-4-5。',
    idPlaceholder: 'claude-sonnet-4-5',
    name: '显示名称',
    namePlaceholder: 'Claude Sonnet 4.5',
    reference: '官方模型 ID',
    referenceHelp: '模型 ID 不是官方 ID 时填写。Maka 据此补全上下文长度、思考档位等资料。',
    referencePlaceholder: '留空表示和模型 ID 相同',
    addFailed: '添加模型失败',
    basics: '基本信息',
    order: '排序',
    orderHelp: '数字小的排在前面。',
    weight: '成本权重',
    weightHelp: '计入额度时乘以这个数。贵的模型可以设大一些。',
    capabilities: '能力',
    capabilitiesHelp: '留空时，Maka 按官方模型 ID 自动补全。',
    contextWindow: '上下文窗口（token）',
    maxOutput: '最大输出（token）',
    thinking: '思考档位',
    thinkingHelp: '员工能选的思考强度。不选表示跟随官方资料。',
    levels: {
      off: '关闭',
      minimal: '最低',
      low: '低',
      medium: '中',
      high: '高',
      xhigh: '很高',
      max: '最高',
    } as Record<string, string>,
    defaultThinking: '默认思考档位',
    defaultThinkingNone: '跟随官方资料',
    imageInput: '图片输入',
    tools: '工具调用',
    capabilityAuto: '自动',
    capabilityYes: '支持',
    capabilityNo: '不支持',
    routes: '路由',
    routesHelp: '请求依次尝试这些模型提供商，前一个在返回前失败时换下一个。',
    noRoutes: '还没有路由，员工选这个模型会发送失败。',
    addRoute: '添加路由',
    routeTitle: '添加路由',
    upstream: '模型提供商',
    upstreamPlaceholder: '选择模型提供商',
    upstreamModel: '提供商那边的模型名',
    upstreamModelHelp:
      '这个模型在该提供商的名字，例如 Vertex 上的 claude-sonnet-4-5@20250929，OpenRouter 上的 anthropic/claude-sonnet-4.5。',
    priority: '优先级',
    priorityInvalid: '填 0 或更大的整数，数字小的先试。',
    routeDetail: (model: string, priority: number) => `${model} · 优先级 ${priority}`,
    routeFailed: '保存路由失败',
    deleteModel: '删除模型',
    deleteTitle: (name: string) => `删除 ${name}？`,
    deleteBody: '员工将不能再选这个模型。已有的用量记录会保留。',
    deleteFailed: '删除模型失败',
    noUpstreams: '还没有模型提供商，请先添加。',
    enable: '启用这个模型',
    enabledHelp: '停用后员工在 Maka 里选不到它。',
  },
  upstreams: {
    title: '模型提供商',
    help: '组织接入的模型提供商。员工的模型请求经这些账号发出，费用也记在它们名下。凭据加密保存，只写不读。',
    add: '添加提供商',
    empty: '还没有模型提供商',
    emptyHelp: '添加一个 Anthropic API、Google Vertex AI 或 OpenRouter 账号。',
    kinds: {
      anthropic: 'Anthropic API',
      vertex: 'Google Vertex AI',
      openrouter: 'OpenRouter',
    } as Record<string, string>,
    modelsUsing: (count: number) => (count === 0 ? '没有模型在用' : `${count} 个模型在用`),
    enableAria: (name: string) => `启用 ${name}`,
    toggleFailed: '修改模型提供商失败',
    addTitle: '添加模型提供商',
    editTitle: (name: string) => `修改 ${name}`,
    keyTitle: (name: string) => `更换 ${name} 的凭据`,
    name: '名称',
    namePlaceholder: '例如 anthropic-prod',
    kind: '类型',
    baseUrl: '服务地址',
    baseUrlHelp: '留空使用 Anthropic 官方地址。',
    apiKey: 'API Key',
    openRouterKeyHelp:
      '在 OpenRouter 的 Keys 页面创建。OpenRouter 建议把 Anthropic 设为首选提供方。',
    projectId: '项目 ID',
    region: '区域',
    regionHelp: '例如 global、us-east5。',
    serviceAccount: '服务账号密钥（JSON）',
    serviceAccountHelp: '粘贴 Google Cloud 服务账号的 JSON 密钥。',
    serviceAccountInvalid: '这不是有效的 JSON 密钥',
    changeKey: '更换凭据…',
    credentialRequired: '请填写凭据',
    saveFailed: '保存模型提供商失败',
    deleteTitle: (name: string) => `删除 ${name}？`,
    deleteBody: '它的凭据会一并删除。还有模型在用时不能删除。',
    deleteFailed: '删除模型提供商失败',
  },
  usage: {
    range: (days: number) => `${days} 天`,
    rangeLabel: '时间范围',
    overview: '概览',
    requests: '请求',
    errors: '失败',
    inputTokens: '输入 token',
    outputTokens: '输出 token',
    units: '加权用量',
    byPerson: '按成员',
    byModel: '按模型',
    columns: {
      person: '成员',
      model: '模型',
      requests: '请求',
      input: '输入',
      output: '输出',
      units: '用量',
    },
    empty: '这段时间没有用量',
    since: (date: string) => `自 ${date} 起`,
  },
  audit: {
    title: '审计日志',
    help: '谁在什么时候做了什么。管理后台和命令行的每次改动都会记在这里。',
    filter: '类型',
    filters: {
      all: '全部',
      'admin.': '管理后台登录',
      'signin.': '登录被拒',
      'session.': '设备会话',
      'user.': '成员',
      'identity.': '登录方式',
      'model.': '模型',
      'upstream.': '模型提供商',
      'quota.': '额度',
    } as Record<string, string>,
    columns: { time: '时间', actor: '操作者', action: '操作', target: '对象' },
    system: '系统',
    organizationDefault: '组织默认',
    cli: '命令行',
    loadMore: '加载更多',
    empty: '没有记录',
    actions: {
      'admin.signed_in': '登录管理后台',
      'admin.signed_out': '退出管理后台',
      'admin.signin_refused': '被拒绝进入管理后台',
      'signin.refused': '登录被拒',
      'session.created': '设备登录',
      'session.revoked': '设备退出登录',
      'user.role_changed': '修改角色',
      'user.deactivated': '停用成员',
      'user.activated': '重新启用成员',
      'identity.unlinked': '解除登录方式绑定',
      'identity.linked': '绑定登录方式',
      'identity.conflict': '登录方式冲突',
      'user.created': '新成员加入',
      'model.created': '添加模型',
      'model.updated': '修改模型',
      'model.deleted': '删除模型',
      'model.routed': '修改模型路由',
      'upstream.created': '添加模型提供商',
      'upstream.updated': '修改模型提供商',
      'upstream.deleted': '删除模型提供商',
      'quota.set': '设置额度',
      'quota.removed': '移除额度',
    } as Record<string, string>,
  },
};

export type ConsoleCopy = Widen<typeof zh>;

const en: ConsoleCopy = {
  product: 'Maka Admin',
  notFound: {
    title: "We couldn't find that page",
    body: 'The address may be mistyped, or the page is no longer here.',
    home: 'Go to the console',
    back: 'Go back',
    memberTitle: "We couldn't find that member",
    memberBody: 'The link may be incomplete, or it does not point to a member.',
    modelTitle: "We couldn't find that model",
    modelBody: 'It may have been deleted, or the link is incomplete.',
    toMembers: 'Back to members',
    toModels: 'Back to models',
  },
  login: {
    title: 'Sign in to Maka Admin',
    continueWith: (provider) => `Continue with ${provider}`,
    or: 'OR',
    loading: 'Loading sign-in options…',
    loadFailed: 'The server cannot be reached right now.',
    retry: 'Try again',
    foot: 'Only organization administrators can sign in.',
    failures: {
      expired: 'That sign-in expired. Sign in again.',
      cancelled: 'Signing in did not finish. Sign in again.',
      not_admin: 'This account is not an organization administrator.',
      email_not_verified: "This account's email address is not verified.",
      domain_not_allowed: 'This email domain cannot sign in.',
      account_deactivated: 'This account has been deactivated.',
      identity_conflict: 'This email belongs to another account. Ask an administrator.',
      provider_error: 'The identity provider could not sign you in. Try again later.',
    },
  },
  nav: {
    label: 'Admin console',
    groups: { organization: 'Organization', models: 'Models', records: 'Records' },
    members: 'Members',
    quotas: 'Allowances',
    models: 'Models',
    upstreams: 'LLM Provider',
    usage: 'Usage',
    audit: 'Audit log',
    signOut: 'Sign out',
    signOutFailed: 'Could not sign out',
    back: (label) => `Back to ${label}`,
  },
  common: {
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    add: 'Add',
    remove: 'Remove',
    delete: 'Delete',
    edit: 'Edit…',
    manage: 'Manage',
    manageAria: (name) => `Manage ${name}`,
    moreActions: (name) => `More actions for ${name}`,
    loading: 'Loading',
    loadFailed: 'Could not load',
    retry: 'Retry',
    saveFailed: 'Could not save',
    requestFailed: (status) => `The server did not complete the request (${status})`,
    unreachable: 'The server cannot be reached. Check the network and try again.',
    consoleUnavailable: 'The console cannot be opened right now',
    disabled: 'Off',
    unlimited: 'Unlimited',
    never: 'Never',
    units: (value) => `${value} units`,
  },
  members: {
    title: 'Members',
    help: 'People who have signed in to Maka with their company account. Someone new joins the first time they sign in.',
    search: 'Search by name or email',
    columns: { person: 'Member', role: 'Role', lastLogin: 'Last sign-in', devices: 'Devices' },
    admin: 'Admin',
    member: 'Member',
    deactivated: 'Deactivated',
    devicesOnline: (count) =>
      count === 0 ? 'None' : count === 1 ? '1 signed in' : `${count} signed in`,
    empty: 'Nobody has signed in yet',
    emptyHelp: 'People appear here after they sign in to Maka with their company account.',
    noMatch: 'No matching members',
    open: (name) => `Open ${name}`,
  },
  member: {
    account: 'Account',
    role: 'Role',
    roleHelp: 'Admins can open this console.',
    roleFailed: 'Could not change the role',
    active: 'Active',
    activeHelp: "Can sign in to Maka and use the company's models.",
    deactivatedHelp: 'Signed out on every device and cannot sign in.',
    deactivate: 'Deactivate…',
    activate: 'Reactivate',
    deactivateTitle: (name) => `Deactivate ${name}?`,
    deactivateBody:
      'They are signed out on every device at once and cannot sign in again until reactivated.',
    statusFailed: 'Could not change the status',
    lastLogin: 'Last sign-in',
    joined: 'Joined',
    identities: 'Sign-in methods',
    identitiesHelp: 'The identity provider accounts this person signs in with.',
    noIdentities: 'No linked identity provider',
    unlink: 'Unlink…',
    unlinkTitle: (provider) => `Unlink ${provider}?`,
    unlinkBody:
      'Devices signed in through it are signed out. Signing in through it again links it back to the same email.',
    unlinkFailed: 'Could not unlink',
    devices: 'Devices',
    devicesHelp: 'Maka desktops they have signed in on, the 20 most recent.',
    noDevices: 'Not signed in on any device yet',
    unnamedDevice: 'Unnamed device',
    online: 'Signed in',
    signedOut: 'Signed out',
    sessionExpired: 'Sign-in expired',
    deviceDetail: (provider, lastUsed, since) =>
      `Through ${provider} · last used ${lastUsed} · signed in ${since}`,
    revoke: 'Sign out…',
    revokeTitle: (device) => `Sign ${device} out?`,
    revokeBody:
      "The device is signed out at once and must sign in again to use the company's models.",
    revokeFailed: 'Could not sign the device out',
    revokeReasons: {
      account_deactivated: 'account deactivated',
      identity_unlinked: 'sign-in unlinked',
      admin_revoked: 'by an admin',
      signed_out: 'signed out',
      code_reuse: 'security',
      refresh_token_reuse: 'security',
    },
    quotas: 'Allowances',
    quotasHelp: 'How much weighted usage this person may use each period.',
    week: 'Weekly',
    month: 'Monthly',
    quotaUsage: (used, limit, resets) => `${used} of ${limit} used · resets ${resets}`,
    quotaUnlimited: (used) => `Unlimited · ${used} used this period`,
    quotaSource: { user: 'their own', default: 'organization default', none: '' },
    setQuota: 'Set…',
  },
  quotas: {
    defaults: 'Organization defaults',
    defaultsHelp: 'How much weighted usage each person may use per period. Unset means unlimited.',
    week: 'Weekly',
    weekHelp: 'Resets every Monday at 00:00 UTC.',
    month: 'Monthly',
    monthHelp: 'Resets on the 1st at 00:00 UTC.',
    people: 'Individual allowances',
    peopleHelp: 'Set for particular members, in place of the defaults.',
    addPerson: 'Add',
    columns: { person: 'Member', week: 'Weekly', month: 'Monthly' },
    noPeople: 'Nobody has an allowance of their own',
    inherit: 'Default',
    units:
      "Units are weighted tokens: input ×1, output ×5, cache writes ×1.25, cache reads ×0.1, times the model's cost weight.",
    dialogTitle: (what) => `Set the ${what.toLowerCase()} allowance`,
    limit: 'Allowance (units)',
    limitPlaceholder: 'For example 5000000',
    unlimitedChoice: 'Unlimited',
    inheritChoice: 'Use the organization default',
    personField: 'Member',
    personPlaceholder: 'Choose a member',
    periodField: 'Period',
    invalidLimit: 'Enter a number, 0 or more',
    failed: 'Could not save the allowance',
  },
  models: {
    title: 'Models',
    help: 'The models people can pick in Maka. Once on, everyone can use them.',
    add: 'Add model',
    empty: 'No models yet',
    emptyHelp:
      'Add an LLM provider first, then add models and choose the provider each goes through.',
    noRoute: 'No route',
    via: (names) => `Through ${names}`,
    enableAria: (name) => `Turn on ${name}`,
    toggleFailed: 'Could not change the model',
    addTitle: 'Add a model',
    id: 'Model ID',
    idHelp: "The name Maka asks for. Prefer the vendor's own ID, such as claude-sonnet-4-5.",
    idPlaceholder: 'claude-sonnet-4-5',
    name: 'Display name',
    namePlaceholder: 'Claude Sonnet 4.5',
    reference: 'Vendor model ID',
    referenceHelp:
      "When the model ID is not the vendor's. Maka fills in context length, thinking levels and more from it.",
    referencePlaceholder: 'Empty means the same as the model ID',
    addFailed: 'Could not add the model',
    basics: 'Basics',
    order: 'Order',
    orderHelp: 'Lower numbers come first.',
    weight: 'Cost weight',
    weightHelp: 'Usage counts against allowances times this. Set it higher for costlier models.',
    capabilities: 'Capabilities',
    capabilitiesHelp: 'Empty fields are filled in from the vendor model ID.',
    contextWindow: 'Context window (tokens)',
    maxOutput: 'Maximum output (tokens)',
    thinking: 'Thinking levels',
    thinkingHelp: "The thinking levels people can pick. None means the vendor's own.",
    levels: {
      off: 'Off',
      minimal: 'Minimal',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      xhigh: 'Extra high',
      max: 'Max',
    },
    defaultThinking: 'Default thinking level',
    defaultThinkingNone: "The vendor's own",
    imageInput: 'Image input',
    tools: 'Tool use',
    capabilityAuto: 'Automatic',
    capabilityYes: 'Supported',
    capabilityNo: 'Not supported',
    routes: 'Routes',
    routesHelp:
      'Requests try these providers in turn; the next takes over when one fails before answering.',
    noRoutes: 'No routes yet: sending with this model fails.',
    addRoute: 'Add route',
    routeTitle: 'Add a route',
    upstream: 'LLM provider',
    upstreamPlaceholder: 'Choose an LLM provider',
    upstreamModel: 'Model name at the provider',
    upstreamModelHelp:
      "This model's name at that provider, such as claude-sonnet-4-5@20250929 on Vertex or anthropic/claude-sonnet-4.5 on OpenRouter.",
    priority: 'Priority',
    priorityInvalid: 'A whole number, 0 or more; lower goes first.',
    routeDetail: (model, priority) => `${model} · priority ${priority}`,
    routeFailed: 'Could not save the routes',
    deleteModel: 'Delete model',
    deleteTitle: (name) => `Delete ${name}?`,
    deleteBody: 'People can no longer pick it. Its usage records stay.',
    deleteFailed: 'Could not delete the model',
    noUpstreams: 'No LLM providers yet. Add one first.',
    enable: 'Offer this model',
    enabledHelp: 'Turned off, people cannot pick it in Maka.',
  },
  upstreams: {
    title: 'LLM Provider',
    help: "The LLM providers the organization is connected to. People's model requests go out through these accounts and are billed to them. Credentials are stored encrypted on the server, and can be replaced but never read back.",
    add: 'Add provider',
    empty: 'No LLM providers yet',
    emptyHelp: 'Add an Anthropic API, Google Vertex AI or OpenRouter account.',
    kinds: { anthropic: 'Anthropic API', vertex: 'Google Vertex AI', openrouter: 'OpenRouter' },
    modelsUsing: (count) =>
      count === 0 ? 'No model uses it' : count === 1 ? '1 model uses it' : `${count} models use it`,
    enableAria: (name) => `Turn on ${name}`,
    toggleFailed: 'Could not change the provider',
    addTitle: 'Add an LLM provider',
    editTitle: (name) => `Edit ${name}`,
    keyTitle: (name) => `Replace the credential of ${name}`,
    name: 'Name',
    namePlaceholder: 'For example anthropic-prod',
    kind: 'Kind',
    baseUrl: 'Service address',
    baseUrlHelp: "Empty uses Anthropic's own address.",
    apiKey: 'API key',
    openRouterKeyHelp:
      "Create one on OpenRouter's Keys page. OpenRouter recommends Anthropic as the preferred provider.",
    projectId: 'Project ID',
    region: 'Region',
    regionHelp: 'For example global or us-east5.',
    serviceAccount: 'Service account key (JSON)',
    serviceAccountHelp: "Paste the Google Cloud service account's JSON key.",
    serviceAccountInvalid: 'This is not a valid JSON key',
    changeKey: 'Replace credential…',
    credentialRequired: 'Enter the credential',
    saveFailed: 'Could not save the provider',
    deleteTitle: (name) => `Delete ${name}?`,
    deleteBody: 'Its credential is deleted with it. It cannot be deleted while models use it.',
    deleteFailed: 'Could not delete the provider',
  },
  usage: {
    range: (days) => `${days} days`,
    rangeLabel: 'Period',
    overview: 'Overview',
    requests: 'Requests',
    errors: 'Failed',
    inputTokens: 'Input tokens',
    outputTokens: 'Output tokens',
    units: 'Weighted usage',
    byPerson: 'By member',
    byModel: 'By model',
    columns: {
      person: 'Member',
      model: 'Model',
      requests: 'Requests',
      input: 'Input',
      output: 'Output',
      units: 'Usage',
    },
    empty: 'No usage in this period',
    since: (date) => `Since ${date}`,
  },
  audit: {
    title: 'Audit log',
    help: 'Who did what, and when. Every change made here or on the command line is recorded.',
    filter: 'Kind',
    filters: {
      all: 'All',
      'admin.': 'Console sign-ins',
      'signin.': 'Refused sign-ins',
      'session.': 'Device sessions',
      'user.': 'Members',
      'identity.': 'Sign-in methods',
      'model.': 'Models',
      'upstream.': 'LLM providers',
      'quota.': 'Allowances',
    },
    columns: { time: 'Time', actor: 'By', action: 'Action', target: 'Target' },
    system: 'System',
    organizationDefault: 'Organization default',
    cli: 'Command line',
    loadMore: 'Load more',
    empty: 'Nothing recorded',
    actions: {
      'admin.signed_in': 'Signed in to the console',
      'admin.signed_out': 'Signed out of the console',
      'admin.signin_refused': 'Refused entry to the console',
      'signin.refused': 'Sign-in refused',
      'session.created': 'Device signed in',
      'session.revoked': 'Device signed out',
      'user.role_changed': 'Role changed',
      'user.deactivated': 'Member deactivated',
      'user.activated': 'Member reactivated',
      'identity.unlinked': 'Sign-in method unlinked',
      'identity.linked': 'Sign-in method linked',
      'identity.conflict': 'Sign-in method conflict',
      'user.created': 'Member joined',
      'model.created': 'Model added',
      'model.updated': 'Model changed',
      'model.deleted': 'Model deleted',
      'model.routed': 'Model routes changed',
      'upstream.created': 'LLM provider added',
      'upstream.updated': 'LLM provider changed',
      'upstream.deleted': 'LLM provider deleted',
      'quota.set': 'Allowance set',
      'quota.removed': 'Allowance removed',
    },
  },
};

export function consoleLocale(): ConsoleLocale {
  return navigator.language?.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en';
}

export function getCopy(locale: ConsoleLocale): ConsoleCopy {
  return locale === 'zh-CN' ? zh : en;
}
